apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  labels:
    name: app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app-api
  template:
    metadata:
      labels:
        service: app-api
    spec:
      containers:
      - name: app-api
        image: 832444123412.dkr.ecr.us-west-2.amazonaws.com/coworkingspace:3
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          value: postgres
        - name: DB_PASSWORD
          value: postgres
      restartPolicy: Always
